# Generated by Django 5.2.12 on 2026-03-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hat',
            name='code',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Boş bırakılırsa ad alanından otomatik üretilir (Türkçe harfler korunur).', max_length=64, unique=True, verbose_name='kod'),
        ),
    ]
