# Generated by Django 5.2.12 on 2026-03-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_safedelete_and_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='hat',
            name='is_coordination_hat',
            field=models.BooleanField(default=False, help_text='İlçe kullanıcısı: yalnızca kendi ilçesindeki tüm hatların etkinliklerini görür. İl yetkilisi: il genelinde tüm hatların etkinliklerini görür; isteğe bağlı ilçe filtresi kullanılabilir.', verbose_name='koordinasyon hattı (Ana Kademe)'),
        ),
        migrations.AddField(
            model_name='historicalhat',
            name='is_coordination_hat',
            field=models.BooleanField(default=False, help_text='İlçe kullanıcısı: yalnızca kendi ilçesindeki tüm hatların etkinliklerini görür. İl yetkilisi: il genelinde tüm hatların etkinliklerini görür; isteğe bağlı ilçe filtresi kullanılabilir.', verbose_name='koordinasyon hattı (Ana Kademe)'),
        ),
    ]
