# Generated by Django 5.2.12 on 2026-03-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_coordination_hat'),
    ]

    operations = [
        migrations.AddField(
            model_name='hat',
            name='coordination_bucket',
            field=models.CharField(blank=True, choices=[('ana_kademe', 'Ana Kademe'), ('genclik', 'Gençlik Kolları'), ('kadin', 'Kadın Kolları'), ('komisyon', 'Komisyonlar')], help_text='Koordinasyon kullanıcıları kol süzgecinde (Ana Kademe / Gençlik / Kadın / Komisyon) bu hattı gruplar. Boş bırakılırsa kol süzgeci bu hatı listelemez.', max_length=32, null=True, verbose_name='koordinasyon kolu'),
        ),
        migrations.AddField(
            model_name='historicalhat',
            name='coordination_bucket',
            field=models.CharField(blank=True, choices=[('ana_kademe', 'Ana Kademe'), ('genclik', 'Gençlik Kolları'), ('kadin', 'Kadın Kolları'), ('komisyon', 'Komisyonlar')], help_text='Koordinasyon kullanıcıları kol süzgecinde (Ana Kademe / Gençlik / Kadın / Komisyon) bu hattı gruplar. Boş bırakılırsa kol süzgeci bu hatı listelemez.', max_length=32, null=True, verbose_name='koordinasyon kolu'),
        ),
    ]
