# Generated by Django 5.2.12 on 2026-03-21 18:03

from django.db import migrations, models


def clear_komisyon_bucket(apps, schema_editor):
    Hat = apps.get_model("org", "Hat")
    HistoricalHat = apps.get_model("org", "HistoricalHat")
    Hat.objects.filter(coordination_bucket="komisyon").update(
        coordination_bucket=None,
    )
    HistoricalHat.objects.filter(coordination_bucket="komisyon").update(
        coordination_bucket=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_coordination_bucket'),
    ]

    operations = [
        migrations.RunPython(clear_komisyon_bucket, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='hat',
            name='coordination_bucket',
            field=models.CharField(blank=True, choices=[('ana_kademe', 'Ana Kademe'), ('genclik', 'Gençlik Kolları'), ('kadin', 'Kadın Kolları')], help_text='Koordinasyon kullanıcıları kol süzgecinde (Ana Kademe / Gençlik / Kadın) bu hattı gruplar. Boş bırakılırsa kol süzgeci bu hatı listelemez.', max_length=32, null=True, verbose_name='koordinasyon kolu'),
        ),
        migrations.AlterField(
            model_name='historicalhat',
            name='coordination_bucket',
            field=models.CharField(blank=True, choices=[('ana_kademe', 'Ana Kademe'), ('genclik', 'Gençlik Kolları'), ('kadin', 'Kadın Kolları')], help_text='Koordinasyon kullanıcıları kol süzgecinde (Ana Kademe / Gençlik / Kadın) bu hattı gruplar. Boş bırakılırsa kol süzgeci bu hatı listelemez.', max_length=32, null=True, verbose_name='koordinasyon kolu'),
        ),
    ]
