# Generated by Django 5.2.12 on 2026-03-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_remove_komisyon_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='hat',
            name='coordination_line',
            field=models.CharField(blank=True, choices=[('ilce_baskanligi', 'İlçe Başkanlığı'), ('komisyon', 'Komisyon')], help_text='Kol seçildiğinde hat süzgecinde: İlçe Başkanlıkları veya Komisyonlar grubunda gösterilir. Kol ile birlikte doldurulmalıdır.', max_length=32, null=True, verbose_name='kol içi hat türü'),
        ),
        migrations.AddField(
            model_name='historicalhat',
            name='coordination_line',
            field=models.CharField(blank=True, choices=[('ilce_baskanligi', 'İlçe Başkanlığı'), ('komisyon', 'Komisyon')], help_text='Kol seçildiğinde hat süzgecinde: İlçe Başkanlıkları veya Komisyonlar grubunda gösterilir. Kol ile birlikte doldurulmalıdır.', max_length=32, null=True, verbose_name='kol içi hat türü'),
        ),
    ]
