# Generated by Django 5.2.12 on 2026-03-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_coordination_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hat',
            name='coordination_line',
            field=models.CharField(blank=True, choices=[('il_baskanligi', 'İl Başkanlığı'), ('ilce_baskanligi', 'İlçe Başkanlığı'), ('komisyon', 'Komisyon')], help_text='Kol seçildiğinde hat süzgecinde: İl Başkanlığı, İlçe Başkanlıkları veya Komisyonlar grubunda gösterilir. Kol ile birlikte doldurulmalıdır.', max_length=32, null=True, verbose_name='kol içi hat türü'),
        ),
        migrations.AlterField(
            model_name='historicalhat',
            name='coordination_line',
            field=models.CharField(blank=True, choices=[('il_baskanligi', 'İl Başkanlığı'), ('ilce_baskanligi', 'İlçe Başkanlığı'), ('komisyon', 'Komisyon')], help_text='Kol seçildiğinde hat süzgecinde: İl Başkanlığı, İlçe Başkanlıkları veya Komisyonlar grubunda gösterilir. Kol ile birlikte doldurulmalıdır.', max_length=32, null=True, verbose_name='kol içi hat türü'),
        ),
    ]
