# Generated by Django 5.2 on 2026-03-24 15:11
#
# Not: Bazı ortamlarda org_historicaldistrict / org_historicalhat üzerinde
# election_zone sütunu zaten vardır (manuel veya önceki deneme). Bu yüzden
# AddField veritabanında DuplicateColumn üretmesin diye SeparateDatabaseAndState
# kullanılıyor; eksik sütunlar RunPython ile koşullu eklenir.

import django.core.validators
from django.db import migrations, models


def _table_has_column(schema_editor, table: str, column: str) -> bool:
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        if conn.vendor == "sqlite":
            cursor.execute(f'PRAGMA table_info("{table}")')
            return any(row[1] == column for row in cursor.fetchall())
        cursor.execute(
            """
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = %s AND column_name = %s
            """,
            [table, column],
        )
        return cursor.fetchone() is not None


def ensure_history_election_zone_columns(apps, schema_editor):
    """Historical tablolarda election_zone yoksa ekle (DuplicateColumn önlenir)."""
    HistoricalDistrict = apps.get_model("org", "HistoricalDistrict")
    HistoricalHat = apps.get_model("org", "HistoricalHat")
    for Model in (HistoricalDistrict, HistoricalHat):
        table = Model._meta.db_table
        if _table_has_column(schema_editor, table, "election_zone"):
            continue
        if schema_editor.connection.vendor == "sqlite":
            sql = f'ALTER TABLE "{table}" ADD COLUMN election_zone integer NULL'
        else:
            sql = f'ALTER TABLE "{table}" ADD COLUMN election_zone smallint NULL'
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(sql)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0010_hat_election_zone"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelOptions(
                    name="district",
                    options={
                        "ordering": ["election_zone", "name", "id"],
                        "verbose_name": "İlçe",
                        "verbose_name_plural": "İlçeler",
                    },
                ),
                migrations.AddField(
                    model_name="historicaldistrict",
                    name="election_zone",
                    field=models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="İstanbul milletvekili seçim bölgesi (1, 2 veya 3). İl Başkanlığı görünümünde ilçeler bu alana göre gruplanır.",
                        null=True,
                        verbose_name="seçim bölgesi",
                    ),
                ),
                migrations.AddField(
                    model_name="historicalhat",
                    name="election_zone",
                    field=models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="İstanbul milletvekili seçim bölgesi (1, 2 veya 3). Ana Kademe İlçe Başkanlığı hatları için İl Başkanlığı sidebar sekmelerinde kullanılır.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="seçim bölgesi",
                    ),
                ),
                migrations.AlterField(
                    model_name="hat",
                    name="code",
                    field=models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="Boş bırakılırsa ad alanından otomatik üretilir: önce Türkçe harfler İngilizce karşılıklarına çevrilir, sonra koddaki gibi kısa bir slug üretilir.",
                        max_length=64,
                        unique=True,
                        verbose_name="kod",
                    ),
                ),
                migrations.AlterField(
                    model_name="historicalhat",
                    name="code",
                    field=models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="Boş bırakılırsa ad alanından otomatik üretilir: önce Türkçe harfler İngilizce karşılıklarına çevrilir, sonra koddaki gibi kısa bir slug üretilir.",
                        max_length=64,
                        verbose_name="kod",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    ensure_history_election_zone_columns,
                    noop_reverse,
                ),
                migrations.AlterField(
                    model_name="hat",
                    name="code",
                    field=models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="Boş bırakılırsa ad alanından otomatik üretilir: önce Türkçe harfler İngilizce karşılıklarına çevrilir, sonra koddaki gibi kısa bir slug üretilir.",
                        max_length=64,
                        unique=True,
                        verbose_name="kod",
                    ),
                ),
                migrations.AlterField(
                    model_name="historicalhat",
                    name="code",
                    field=models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="Boş bırakılırsa ad alanından otomatik üretilir: önce Türkçe harfler İngilizce karşılıklarına çevrilir, sonra koddaki gibi kısa bir slug üretilir.",
                        max_length=64,
                        verbose_name="kod",
                    ),
                ),
            ],
        ),
    ]
