# Generated by Django 5.2.12 on 2026-03-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_provincial_official',
            field=models.BooleanField(default=False, help_text='İşaretlenirse ilçe profilde boş olabilir; etkinlik oluştururken ilçe istemci tarafından seçilir. Hat atanması yine zorunludur.', verbose_name='il yetkilisi'),
        ),
    ]
