# Generated by Django 5.2.12 on 2026-03-20 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='başlık')),
                ('description', models.TextField(verbose_name='açıklama')),
                ('starts_at', models.DateTimeField(verbose_name='başlangıç')),
                ('status', models.CharField(choices=[('planned', 'Planlandı'), ('completed', 'Tamamlandı')], db_index=True, default='planned', max_length=20, verbose_name='durum')),
                ('location_kind', models.CharField(choices=[('address', 'Adres'), ('map', 'Harita')], max_length=20, verbose_name='konum tipi')),
                ('address_text', models.TextField(blank=True, verbose_name='adres metni')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='enlem')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='boylam')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='tamamlanma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='org.district', verbose_name='ilçe')),
                ('hat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='org.hat', verbose_name='hat')),
            ],
            options={
                'verbose_name': 'Etkinlik',
                'verbose_name_plural': 'Etkinlikler',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='özet')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('review', 'İncelemede'), ('published', 'Yayında')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='events.event')),
            ],
            options={
                'verbose_name': 'Etkinlik raporu',
                'verbose_name_plural': 'Etkinlik raporları',
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reports/%Y/%m/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.eventreport')),
            ],
            options={
                'verbose_name': 'Rapor görseli',
                'verbose_name_plural': 'Rapor görselleri',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
