# Generated by Django 5.1.6 on 2026-03-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chpist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedevent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
