# Generated by Django 5.2 on 2026-03-24 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_demo_membership(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    OrgUnit = apps.get_model('chpist', 'OrgUnit')
    OrgMembership = apps.get_model('chpist', 'OrgMembership')
    u = User.objects.filter(username='demo').first()
    ou = OrgUnit.objects.filter(
        geographic_node__code='zeytinburnu',
        branch='ana_kademe',
        commission__isnull=True,
    ).first()
    if u and ou and not OrgMembership.objects.filter(user=u, org_unit=ou).exists():
        OrgMembership.objects.create(
            user=u,
            org_unit=ou,
            role='delegate',
            title='İlçe yöneticisi (örnek)',
            is_primary=True,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chpist', '0003_hierarchy_org_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Üye'), ('delegate', 'Temsilci'), ('chair', 'Başkan'), ('coordinator', 'Koordinatör')], db_index=True, default='member', max_length=32)),
                ('title', models.CharField(blank=True, help_text='Görünen unvan (örn. İlçe Başkan Yardımcısı).', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Üst çubukta varsayılan olarak gösterilecek birim.')),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chpist.orgunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'org_unit_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'org_unit'), name='uniq_org_membership_user_org_unit')],
            },
        ),
        migrations.RunPython(seed_demo_membership, noop_reverse),
    ]
