# Generated by Django 5.2 on 2026-03-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chpist', '0004_org_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_description',
            field=models.TextField(blank=True, help_text='Kaynak planlanan etkinliğin açıklaması.'),
        ),
        migrations.AddField(
            model_name='post',
            name='event_title',
            field=models.CharField(blank=True, help_text='Kaynak planlanan etkinliğin başlığı (akışta gösterilir).', max_length=300),
        ),
    ]
