# Generated by Django 5.2 on 2026-03-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chpist', '0005_post_event_title_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_location',
            field=models.TextField(blank=True, help_text='Etkinlik yeri (planlama / tamamlama anından kopyalanır, düzenlenebilir).'),
        ),
        migrations.AddField(
            model_name='post',
            name='event_start_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Planlanan etkinlik başlangıcı (tamamlanan gönderilerde gösterim / düzenleme).', null=True),
        ),
    ]
